characterId: demo_char
layers:
  - name: torso
    file: torso.png
    type: core
    parent: root
    pivot: { x: 0.5, y: 0.5 }
  - name: head
    file: head.png
    type: head
    parent: torso
    pivot: { x: 0.5, y: 0.4 }
  - name: leftArm
    file: left_arm.png
    type: limb
    parent: torso
    pivot: { x: 0.15, y: 0.8 }
  - name: leftHand
    file: left_hand.png
    type: limbEnd
    parent: leftArm
    pivot: { x: 0.5, y: 0.5 }
  - name: rightArm
    file: right_arm.png
    type: limb
    parent: torso
    pivot: { x: 0.85, y: 0.8 }
  - name: rightHand
    file: right_hand.png
    type: limbEnd
    parent: rightArm
    pivot: { x: 0.5, y: 0.5 }
animations:
  idle:
    enable: true
    breathing: { target: torso, scaleY: 0.02, period: 2.0 }
    headSwing: { target: head, rotDeg: 3, period: 2.4 }
